version: "3"

services:
  api:
    build: ./
    hostname: api
    container_name: api
    ports:
      - 4000:4000
    volumes:
      - ./src:/home/appuser/app
      - /home/appuser/app/node_modules
    networks:
      - broker_network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: >
      -- requirepass password 
    volumes:
      - redis-data:/data
    networks:
      - broker_network
  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - 27017:27017
      volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
  elastic:
    image: elasticsearch:6.8.20
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - broker_network
  kibana:
    image: kibana:6.8.20
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - broker_network
volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mongo-config:
  elastic-data:
networks:
  broker_network:
    driver: bridge